package org.myproject.hello;

import org.myproject.hello.entity.*;
import org.myproject.hello.repository.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Configuration
public class LoadDatabase {

    @Bean
    CommandLineRunner initDatabase(
            MemberRepository memberRepository,
            OwnerRepository ownerRepository,
            PetRepository petRepository,
            PetTypeRepository petTypeRepository,
            SpecialityRepository specialityRepository,
            VetRepository vetRepository,
            VisitRepository visitRepository,
            VetSpecialityRepository vetSpecialityRepository,
            RoleRepository roleRepository
    ) {
        return args -> {
            Vet vet1 = new Vet();
            Vet vet2 = new Vet();
            Vet vet3 = new Vet();
            Vet vet4 = new Vet();
            Vet vet5 = new Vet();
            Vet vet6 = new Vet();
            vet1.setFirstName("James");
            vet1.setLastName("Carter");
            vet2.setFirstName("Helen");
            vet2.setLastName("Leary");
            vet3.setFirstName("Linda");
            vet3.setLastName("Douglas");
            vet4.setFirstName("Rafael");
            vet4.setLastName("Ortega");
            vet5.setFirstName("Henry");
            vet5.setLastName("Stevens");
            vet6.setFirstName("Sharon");
            vet6.setLastName("Jenkins");
            vetRepository.save(vet1);
            vetRepository.save(vet2);
            vetRepository.save(vet3);
            vetRepository.save(vet4);
            vetRepository.save(vet5);
            vetRepository.save(vet6);

            Speciality speciality1 = new Speciality();
            Speciality speciality2 = new Speciality();
            Speciality speciality3 = new Speciality();
            speciality1.setName("radiology");
            speciality2.setName("surgery");
            speciality3.setName("dentistry");
            specialityRepository.save(speciality1);
            specialityRepository.save(speciality2);
            specialityRepository.save(speciality3);

            VetSpeciality vetSpeciality1 = new VetSpeciality();
            VetSpeciality vetSpeciality2 = new VetSpeciality();
            VetSpeciality vetSpeciality3 = new VetSpeciality();
            VetSpeciality vetSpeciality4 = new VetSpeciality();
            VetSpeciality vetSpeciality5 = new VetSpeciality();
            vetSpeciality1.setVet(vet2);
            vetSpeciality1.setSpeciality(speciality1);
            vetSpeciality2.setVet(vet3);
            vetSpeciality2.setSpeciality(speciality2);
            vetSpeciality3.setVet(vet3);
            vetSpeciality3.setSpeciality(speciality3);
            vetSpeciality4.setVet(vet4);
            vetSpeciality4.setSpeciality(speciality2);
            vetSpeciality5.setVet(vet5);
            vetSpeciality5.setSpeciality(speciality1);
            vetSpecialityRepository.save(vetSpeciality1);
            vetSpecialityRepository.save(vetSpeciality2);
            vetSpecialityRepository.save(vetSpeciality3);
            vetSpecialityRepository.save(vetSpeciality4);
            vetSpecialityRepository.save(vetSpeciality5);

            PetType petType1 = new PetType();
            PetType petType2 = new PetType();
            PetType petType3 = new PetType();
            PetType petType4 = new PetType();
            PetType petType5 = new PetType();
            PetType petType6 = new PetType();
            petType1.setName("cat");
            petType2.setName("dog");
            petType3.setName("lizard");
            petType4.setName("snake");
            petType5.setName("bird");
            petType6.setName("hamster");
            petTypeRepository.save(petType1);
            petTypeRepository.save(petType2);
            petTypeRepository.save(petType3);
            petTypeRepository.save(petType4);
            petTypeRepository.save(petType5);
            petTypeRepository.save(petType6);

            Owner owner1 = new Owner();
            Owner owner2 = new Owner();
            Owner owner3 = new Owner();
            Owner owner4 = new Owner();
            Owner owner5 = new Owner();
            Owner owner6 = new Owner();
            Owner owner7 = new Owner();
            Owner owner8 = new Owner();
            Owner owner9 = new Owner();
            Owner owner10 = new Owner();
            owner1.setFirstName("George");
            owner1.setLastName("Franklin");
            owner1.setAddress("110 W. Liberty St.");
            owner1.setCity("Madison");
            owner1.setTelephone("6085551023");
            owner2.setFirstName("Betty");
            owner2.setLastName("Davis");
            owner2.setAddress("638 Cardinal Ave.");
            owner2.setCity("Sun Prairie");
            owner2.setTelephone("6085551749");
            owner3.setFirstName("Eduardo");
            owner3.setLastName("Rodriquez");
            owner3.setAddress("2693 Commerce St.");
            owner3.setCity("McFarland");
            owner3.setTelephone("6085558763");
            owner4.setFirstName("Harold");
            owner4.setLastName("Davis");
            owner4.setAddress("563 Friendly St.");
            owner4.setCity("Windsor");
            owner4.setTelephone("6085553198");
            owner5.setFirstName("Peter");
            owner5.setLastName("McTavish");
            owner5.setAddress("2387 S. Fair Way");
            owner5.setCity("Madison");
            owner5.setTelephone("6085552765");
            owner6.setFirstName("Jean");
            owner6.setLastName("Coleman");
            owner6.setAddress("105 N. Lake St.");
            owner6.setCity("Monona");
            owner6.setTelephone("6085552654");
            owner7.setFirstName("Jeff");
            owner7.setLastName("Black");
            owner7.setAddress("1450 Oak Blvd.");
            owner7.setCity("Monona");
            owner7.setTelephone("6085555387");
            owner8.setFirstName("Maria");
            owner8.setLastName("Escobito");
            owner8.setAddress("345 Maple St.");
            owner8.setCity("Madison");
            owner8.setTelephone("6085557683");
            owner9.setFirstName("David");
            owner9.setLastName("Schroeder");
            owner9.setAddress("2749 Blackhawk Trail");
            owner9.setCity("Madison");
            owner9.setTelephone("6085559435");
            owner10.setFirstName("Carlos");
            owner10.setLastName("Estaban");
            owner10.setAddress("2335 Independence La.");
            owner10.setCity("Waunakee");
            owner10.setTelephone("6085555487");
            ownerRepository.save(owner1);
            ownerRepository.save(owner2);
            ownerRepository.save(owner3);
            ownerRepository.save(owner4);
            ownerRepository.save(owner5);
            ownerRepository.save(owner6);
            ownerRepository.save(owner7);
            ownerRepository.save(owner8);
            ownerRepository.save(owner9);
            ownerRepository.save(owner10);

            Pet pet1 = new Pet();
            Pet pet2 = new Pet();
            Pet pet3 = new Pet();
            Pet pet4 = new Pet();
            Pet pet5 = new Pet();
            Pet pet6 = new Pet();
            Pet pet7 = new Pet();
            Pet pet8 = new Pet();
            Pet pet9 = new Pet();
            Pet pet10 = new Pet();
            Pet pet11 = new Pet();
            Pet pet12 = new Pet();
            Pet pet13 = new Pet();
            pet1.setName("Leo");
            String dateStr1 = "2021-09-07";
            LocalDate date1 = LocalDate.parse(dateStr1);
            LocalDateTime dateTime1 = date1.atStartOfDay();
            pet1.setBirthDate(dateTime1);
            pet1.setType(petType1);
            pet1.setOwner(owner1);
            pet2.setName("Basil");
            String dateStr2 = "2023-08-06";
            LocalDate date2 = LocalDate.parse(dateStr2);
            LocalDateTime dateTime2 = date2.atStartOfDay();
            pet2.setBirthDate(dateTime2);
            pet2.setType(petType6);
            pet2.setOwner(owner2);
            pet3.setName("Rosy");
            String dateStr3 = "2022-04-17";
            LocalDate date3 = LocalDate.parse(dateStr3);
            LocalDateTime dateTime3 = date3.atStartOfDay();
            pet3.setBirthDate(dateTime3);
            pet3.setType(petType2);
            pet3.setOwner(owner3);
            pet4.setName("Jewel");
            String dateStr4 = "2021-03-07";
            LocalDate date4 = LocalDate.parse(dateStr4);
            LocalDateTime dateTime4 = date4.atStartOfDay();
            pet4.setBirthDate(dateTime4);
            pet4.setType(petType2);
            pet4.setOwner(owner3);
            pet5.setName("Iggy");
            String dateStr5 = "2021-11-30";
            LocalDate date5 = LocalDate.parse(dateStr5);
            LocalDateTime dateTime5 = date5.atStartOfDay();
            pet5.setBirthDate(dateTime5);
            pet5.setType(petType3);
            pet5.setOwner(owner4);
            pet6.setName("George");
            String dateStr6 = "2021-01-20";
            LocalDate date6 = LocalDate.parse(dateStr6);
            LocalDateTime dateTime6 = date6.atStartOfDay();
            pet6.setBirthDate(dateTime6);
            pet6.setType(petType4);
            pet6.setOwner(owner5);
            pet7.setName("Samantha");
            String dateStr7 = "2023-09-04";
            LocalDate date7 = LocalDate.parse(dateStr7);
            LocalDateTime dateTime7 = date1.atStartOfDay();
            pet7.setBirthDate(dateTime7);
            pet7.setType(petType1);
            pet7.setOwner(owner6);
            pet8.setName("Max");
            String dateStr8 = "2023-09-04";
            LocalDate date8 = LocalDate.parse(dateStr8);
            LocalDateTime dateTime8 = date8.atStartOfDay();
            pet8.setBirthDate(dateTime8);
            pet8.setType(petType1);
            pet8.setOwner(owner6);
            pet9.setName("Lucky");
            String dateStr9 = "2022-08-06";
            LocalDate date9 = LocalDate.parse(dateStr9);
            LocalDateTime dateTime9 = date9.atStartOfDay();
            pet9.setBirthDate(dateTime9);
            pet9.setType(petType5);
            pet9.setOwner(owner7);
            pet10.setName("Mulligan");
            String dateStr10 = "2018-02-24";
            LocalDate date10 = LocalDate.parse(dateStr10);
            LocalDateTime dateTime10 = date10.atStartOfDay();
            pet10.setBirthDate(dateTime10);
            pet10.setType(petType2);
            pet10.setOwner(owner8);
            pet11.setName("Freddy");
            String dateStr11 = "2021-03-09";
            LocalDate date11 = LocalDate.parse(dateStr11);
            LocalDateTime dateTime11 = date11.atStartOfDay();
            pet11.setBirthDate(dateTime11);
            pet11.setType(petType5);
            pet11.setOwner(owner9);
            pet12.setName("Lucky");
            String dateStr12 = "2021-06-24";
            LocalDate date12 = LocalDate.parse(dateStr12);
            LocalDateTime dateTime12 = date12.atStartOfDay();
            pet12.setBirthDate(dateTime12);
            pet12.setType(petType2);
            pet12.setOwner(owner10);
            pet13.setName("Sly");
            String dateStr13 = "2023-06-08";
            LocalDate date13 = LocalDate.parse(dateStr13);
            LocalDateTime dateTime13 = date13.atStartOfDay();
            pet13.setBirthDate(dateTime13);
            pet13.setType(petType1);
            pet13.setOwner(owner10);
            petRepository.save(pet1);
            petRepository.save(pet2);
            petRepository.save(pet3);
            petRepository.save(pet4);
            petRepository.save(pet5);
            petRepository.save(pet6);
            petRepository.save(pet7);
            petRepository.save(pet8);
            petRepository.save(pet9);
            petRepository.save(pet10);
            petRepository.save(pet11);
            petRepository.save(pet12);
            petRepository.save(pet13);

            Visit visit1 = new Visit();
            Visit visit2 = new Visit();
            Visit visit3 = new Visit();
            Visit visit4 = new Visit();
            visit1.setPet(pet7);
            String dateStrVisit1 = "2024-01-01";
            LocalDate dateVisit1 = LocalDate.parse(dateStrVisit1);
            LocalDateTime dateTimeVisit1 = dateVisit1.atStartOfDay();
            visit1.setDate(dateTimeVisit1);
            visit1.setDescription("rabies shot");
            visit2.setPet(pet8);
            String dateStrVisit2 = "2024-01-02";
            LocalDate dateVisit2 = LocalDate.parse(dateStrVisit2);
            LocalDateTime dateTimeVisit2 = dateVisit2.atStartOfDay();
            visit2.setDate(dateTimeVisit2);
            visit2.setDescription("rabies shot");
            visit3.setPet(pet8);
            String dateStrVisit3 = "2024-01-03";
            LocalDate dateVisit3 = LocalDate.parse(dateStrVisit3);
            LocalDateTime dateTimeVisit3 = dateVisit3.atStartOfDay();
            visit3.setDate(dateTimeVisit3);
            visit3.setDescription("neutered");
            visit4.setPet(pet7);
            String dateStrVisit4 = "2024-01-04";
            LocalDate dateVisit4 = LocalDate.parse(dateStrVisit4);
            LocalDateTime dateTimeVisit4 = dateVisit4.atStartOfDay();
            visit4.setDate(dateTimeVisit4);
            visit4.setDescription("spayed");
            visitRepository.save(visit1);
            visitRepository.save(visit2);
            visitRepository.save(visit3);
            visitRepository.save(visit4);

            Member member = new Member();
            member.setUsername("admin");
            member.setPassword("{noop}admin");
            member.setEnabled(true);
            memberRepository.save(member);

            Role role1 = new Role();
            Role role2 = new Role();
            Role role3 = new Role();
            role1.setMember(member);
            role1.setName("ROLE_OWNER_ADMIN");
            role2.setMember(member);
            role2.setName("ROLE_VET_ADMIN");
            role3.setMember(member);
            role3.setName("ROLE_ADMIN");
            roleRepository.save(role1);
            roleRepository.save(role2);
            roleRepository.save(role3);
        };
    }
}
